spring:
  profiles:
    active: dev
camel:
  springboot:
    shutdownTimeout: 1
    health.indicator.enabled: true
management.security.enabled: false

info.app.name: Spring boiler plate
info.app.description: This is a Spring boot boiler plate code.
info.app.version: 1.0.0

---

spring:
  profiles: mock
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: xyz@gmail.com
    password:
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true

mail.smtp.starttls.enable: true

mailto: xyz@gmail.com
mailFrom: xyz@gmail.com

message:   Hello from MOCK Profile
inputItemQueueEndPoint: direct:input
dataSourceEndPoint: mock:output
selectNodeEndPoint: mock:output1
errorQueueEndPoint: mock:output2
healthEndPoint: direct:health

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: alertsdilip@gmail.com
  #    password: alertsdilip123
  #    properties.mail.smtp.auth:  true
  #    properties.mail.smtp.starttls.enable: true
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    #packages.trust-all: true



mailto: alertsdilip@gmail.com
mailFrom: alertsdilip@gmail.com
message:   Hello from DEV Profile
inputItemQueueEndPoint: jms:queue:inputItemQueue
inboxFileEndPoint: file:inbox
dataSourceEndPoint: jdbc:dataSource
errorQueueEndPoint:  jms:queue:errorItemQueue
selectNodeEndPoint: sql:select * from items where sku = :#skuId?dataSource=#dataSource
healthEndPoint: timer:health?period=10s

---

spring:
  profiles: stage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: alertsdilip@gmail.com
    password: alertsdilip123
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true

mailto: alertsdilip@gmail.com
mailFrom: alertsdilip@gmail.com
message:    Hello from STAGE Profile

inputItemQueueEndPoint: jms:queue:inputItemQueue
dataSourceEndPoint: jdbc:dataSource
errorQueueEndPoint:  jms:queue:errorItemQueue
selectNodeEndPoint: sql:select * from items where sku = :#skuId?dataSource=#dataSource
healthEndPoint: timer:health?period=10s

---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: alertsdilip@gmail.com
    password: alertsdilip123
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true

mailto: alertsdilip@gmail.com
mailFrom: alertsdilip@gmail.com

message:    Hello from PROD Profile

inputItemQueueEndPoint: jms:queue:inputItemQueue
dataSourceEndPoint: jdbc:dataSource
errorQueueEndPoint:  jms:queue:errorItemQueue
selectNodeEndPoint: sql:select * from items where sku = :#skuId?dataSource=#dataSource
healthEndPoint: timer:health?period=10s

---